name: Lint, Format, and Analyze Code

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13.1'

      - name: Cache pip dependencies
        uses: actions/cache@v3  # Update to v3 here
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 (Python linting)
        run: |
          pip install flake8
          flake8 .

      - name: Run black (auto-formatting check)
        run: |
          pip install black
          black --check .

      - name: Run pylint (static analysis)
        run: |
          pip install pylint
          pylint TaskAPI

      - name: Run mypy (type checking)
        run: |
          pip install mypy
          mypy TaskAPI
