name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to PythonAnywhere
        env:
          PA_API_TOKEN: ${{ secrets.PA_API_TOKEN }}
        run: |
          echo "Deploying to PythonAnywhere..."
          
          # Ensure PythonAnywhere pulls the latest code from GitHub
          curl -s -X POST \
            -H "Authorization: Token ${PA_API_TOKEN}" \
            -d "action=git_pull" \
            https://www.pythonanywhere.com/api/v0/user/Only1JohnN/webapps/Only1JohnN.pythonanywhere.com/reload/
